In [1]:
#simple imputer exercise 
import numpy as np
import pandas as pd

In [3]:
#practise imputer with categorical values
names=pd.DataFrame({"names":["sila","ali","saliha",np.nan,"efnan","ilayda",np.nan]},index=["a","b","c","d","e","f","g"])

In [4]:
names

names
a    sila
b     ali
c  saliha
d     NaN
e   efnan
f  ilayda
g     NaN

In [6]:
from sklearn.impute import SimpleImputer

In [6]:
from sklearn.impute import SimpleImputer

imputer1=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value="babe")
imputer1.fit_transform(names)

array([['sila'],
       ['ali'],
       ['saliha'],
       ['babe'],
       ['efnan'],
       ['ilayda'],
       ['babe']], dtype=object)

In [8]:
#practise imputer with numerical values
miles=pd.DataFrame({"farthest_run_mile":[50,34,np.nan,13,np.nan,12,np.nan,34,33]})

In [9]:
miles

farthest_run_mile
0               50.0
1               34.0
2                NaN
3               13.0
4                NaN
5               12.0
6                NaN
7               34.0
8               33.0

In [10]:
miles.isna()

farthest_run_mile
0              False
1              False
2               True
3              False
4               True
5              False
6               True
7              False
8              False

In [11]:
miles.isna().sum()

farthest_run_mile    3
dtype: int64

In [14]:
imputer2=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer2.fit_transform(miles)

array([[50.        ],
       [34.        ],
       [29.33333333],
       [13.        ],
       [29.33333333],
       [12.        ],
       [29.33333333],
       [34.        ],
       [33.        ]])

In [15]:
imputer3=SimpleImputer(missing_values=np.nan,strategy="mean",add_indicator=True)
imputer3.fit_transform(miles)

array([[50.        ,  0.        ],
       [34.        ,  0.        ],
       [29.33333333,  1.        ],
       [13.        ,  0.        ],
       [29.33333333,  1.        ],
       [12.        ,  0.        ],
       [29.33333333,  1.        ],
       [34.        ,  0.        ],
       [33.        ,  0.        ]])

In [17]:
imputer4=SimpleImputer(missing_values=np.nan,strategy="median")
imputer4.fit_transform(miles)

array([[50. ],
       [34. ],
       [33.5],
       [13. ],
       [33.5],
       [12. ],
       [33.5],
       [34. ],
       [33. ]])

In [19]:
imputer5=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imputer5.fit_transform(miles)

array([[50.],
       [34.],
       [34.],
       [13.],
       [34.],
       [12.],
       [34.],
       [34.],
       [33.]])

In [20]:
imp_constant_numeric=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=24)

In [21]:
imp_constant_numeric.fit_transform(miles)

array([[50.],
       [34.],
       [24.],
       [13.],
       [24.],
       [12.],
       [24.],
       [34.],
       [33.]])