In [2]:
#simple imputer exercise 
import numpy as np
import pandas as pd

#constant 
#mean
#medium

In [3]:
#practise imputer with categorical values
names=pd.DataFrame({"name":["sila","sila","saliha",np.nan,"efnan","ilayda",np.nan]})

In [4]:
name=names.copy()

In [5]:
from sklearn.impute import SimpleImputer
#because of the data is not a number.We can fill it with constant or most frequent strategy

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imputed_data=simple_imputer.fit_transform(name)
imputed_data


array([['sila'],
       ['sila'],
       ['saliha'],
       ['sila'],
       ['efnan'],
       ['ilayda'],
       ['sila']], dtype=object)

In [6]:
#imputed data is an arr type
#we need a df

type(imputed_data)

numpy.ndarray

In [7]:
#turn it into df

imputed_df=pd.DataFrame(imputed_data,columns=["name"])
imputed_df

name
0    sila
1    sila
2  saliha
3    sila
4   efnan
5  ilayda
6    sila

In [8]:
#fill nan values in real df

name.fillna(imputed_df,inplace=True)
name

name
0    sila
1    sila
2  saliha
3    sila
4   efnan
5  ilayda
6    sila

In [9]:
#lets try to fill the nan values by constant strategy

name=names.copy()

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value="davud")
imputed_data=simple_imputer.fit_transform(name)
imputed_data

array([['sila'],
       ['sila'],
       ['saliha'],
       ['davud'],
       ['efnan'],
       ['ilayda'],
       ['davud']], dtype=object)

In [10]:
#check out the type of imputed data
type(imputed_data)

numpy.ndarray

In [11]:
#turn imputed_data into df
imputed_df=pd.DataFrame(imputed_data,columns=["name"])
imputed_df

name
0    sila
1    sila
2  saliha
3   davud
4   efnan
5  ilayda
6   davud

In [12]:
name.fillna(imputed_df,inplace=True)
name

name
0    sila
1    sila
2  saliha
3   davud
4   efnan
5  ilayda
6   davud

In [13]:
#practise imputer with numerical values
mile=pd.DataFrame({"farthest_run_mile":[50,34,np.nan,13,np.nan,12,np.nan,34,33]})
miles=mile.copy()

In [14]:
miles

farthest_run_mile
0               50.0
1               34.0
2                NaN
3               13.0
4                NaN
5               12.0
6                NaN
7               34.0
8               33.0

In [15]:
miles.isna()

farthest_run_mile
0              False
1              False
2               True
3              False
4               True
5              False
6               True
7              False
8              False

In [16]:
miles.isna().sum()

farthest_run_mile    3
dtype: int64

In [17]:
#we can fill nan values with mean,most_frequent and constant values
#first fill with mean values

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputed_data=simple_imputer.fit_transform(miles)
imputed_data

array([[50.        ],
       [34.        ],
       [29.33333333],
       [13.        ],
       [29.33333333],
       [12.        ],
       [29.33333333],
       [34.        ],
       [33.        ]])

In [18]:
#imputed data is a numpy array we need a df
type(imputed_data)

numpy.ndarray

In [19]:
#turn it into df
imputed_df=pd.DataFrame(imputed_data,columns=["farthest_run_mile"])

#fill null values in miles df
miles.fillna(imputed_df,inplace=True)
miles

farthest_run_mile
0          50.000000
1          34.000000
2          29.333333
3          13.000000
4          29.333333
5          12.000000
6          29.333333
7          34.000000
8          33.000000

In [20]:
#we tried mean and lets go on with median in numerical data
miles=mile.copy()

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="median")
imputed_data=simple_imputer.fit_transform(miles)
imputed_data

array([[50. ],
       [34. ],
       [33.5],
       [13. ],
       [33.5],
       [12. ],
       [33.5],
       [34. ],
       [33. ]])

In [21]:
#we need a df, numpy array instead
imputed_df=pd.DataFrame(imputed_data,columns=["farthest_run_mile"])

#fill the nan in miles df
miles.fillna(imputed_df,inplace=True)
miles

farthest_run_mile
0               50.0
1               34.0
2               33.5
3               13.0
4               33.5
5               12.0
6               33.5
7               34.0
8               33.0

In [22]:
#we also can use most frequent in numerical data
miles=mile.copy()

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imputed_data=simple_imputer.fit_transform(miles)
imputed_data

array([[50.],
       [34.],
       [34.],
       [13.],
       [34.],
       [12.],
       [34.],
       [34.],
       [33.]])

In [25]:
#use constant strategy in simple imputer
miles=mile.copy()

simple_imputer=SimpleImputer(missing_values=np.nan,strategy="constant",fill_value=24)
imputed_data=simple_imputer.fit_transform(miles)
imputed_data

array([[50.],
       [34.],
       [24.],
       [13.],
       [24.],
       [12.],
       [24.],
       [34.],
       [33.]])

In [33]:
#imputed data is an nump array, we need a df

imputed_df=pd.DataFrame(imputed_data,columns=["farthest_run_mile"])
imputed_df

farthest_run_mile
0               50.0
1               34.0
2               24.0
3               13.0
4               24.0
5               12.0
6               24.0
7               34.0
8               33.0

In [34]:
miles.fillna(imputed_df,inplace=True)
miles

farthest_run_mile
0               50.0
1               34.0
2               24.0
3               13.0
4               24.0
5               12.0
6               24.0
7               34.0
8               33.0