In [102]:
#implement all things we learned(till ml7.ipynb)in a new dataset,
import numpy as np
import pandas as pd

In [103]:
data=pd.read_csv("odev_tenis.csv")
df=data.copy()
df

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [104]:
#check for null values
df.isna().sum()

outlook        0
temperature    0
humidity       0
windy          0
play           0
dtype: int64

In [105]:
#turn categorical values into numerical values
#start with outlook, it is nominal categorical val,ohe is better
df["outlook"].unique()

array(['sunny', 'overcast', 'rainy'], dtype=object)

In [106]:
#encode process
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(handle_unknown="ignore",sparse_output=False).set_output(transform="pandas")
ohe_transform=ohe.fit_transform(df[["outlook"]])
ohe_transform


outlook_overcast  outlook_rainy  outlook_sunny
0                0.0            0.0            1.0
1                0.0            0.0            1.0
2                1.0            0.0            0.0
3                0.0            1.0            0.0
4                0.0            1.0            0.0
5                0.0            1.0            0.0
6                1.0            0.0            0.0
7                0.0            0.0            1.0
8                0.0            0.0            1.0
9                0.0            1.0            0.0
10               0.0            0.0            1.0
11               1.0            0.0            0.0
12               1.0            0.0            0.0
13               0.0            1.0            0.0

In [107]:
#eliminate dummy variables and concat

df=pd.concat([df,ohe_transform],axis=1).drop(columns=["outlook"])
df

temperature  humidity  windy play  outlook_overcast  outlook_rainy  \
0            85        85  False   no               0.0            0.0   
1            80        90   True   no               0.0            0.0   
2            83        86  False  yes               1.0            0.0   
3            70        96  False  yes               0.0            1.0   
4            68        80  False  yes               0.0            1.0   
5            65        70   True   no               0.0            1.0   
6            64        65   True  yes               1.0            0.0   
7            72        95  False   no               0.0            0.0   
8            69        70  False  yes               0.0            0.0   
9            75        80  False  yes               0.0            1.0   
10           75        70   True  yes               0.0            0.0   
11           72        90   True  yes               1.0            0.0   
12           81        75  False  yes               1.0            0.0   
13           71        91   True   no               0.0            1.0   

    outlook_sunny  
0             1.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
5             0.0  
6             0.0  
7             1.0  
8             1.0  
9             0.0  
10            1.0  
11            0.0  
12            0.0  
13            0.0

In [108]:
#encode windy column, it is again nominal categorical but values will be binary 0 and 1
#so one hot encoder doesn't provide us any advantage

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df["windy"]=le.fit_transform(df[["windy"]])

#lets encode 'play' column
#it is also nominal categorical column but binary meanwhile
#so labelencoder will be useful

df["play"]=le.fit_transform(df[["play"]])
df




"""
#we can also encode all df and take desired columns easily if there are lots of columns need be encoded.

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

#we can encode 'windy' and 'play'
df_encoded=df.apply(le.fit_transform)

#take only windy and play columns
df_encoded.drop(columns=["temperature","humidity","outlook_rainy","outlook_sunny"],inplace=True)
df.drop(columns=["windy","play"],inplace=True)
df=pd.concat([df,df_encoded],axis=1)
df 
"""


c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


'\n#we can also encode all df and take desired columns easily if there are lots of columns need be encoded.\n\nfrom sklearn.preprocessing import LabelEncoder\n\nle=LabelEncoder()\n\n#we can encode \'windy\' and \'play\'\ndf_encoded=df.apply(le.fit_transform)\n\n#take only windy and play columns\ndf_encoded.drop(columns=["temperature","humidity","outlook_rainy","outlook_sunny"],inplace=True)\ndf.drop(columns=["windy","play"],inplace=True)\ndf=pd.concat([df,df_encoded],axis=1)\ndf \n'

In [109]:
#lets encode 'play' column
#it is also nominal categorical column but binary meanwhile
#so labelencoder will be useful

df["play"]=le.fit_transform(df[["play"]])
df

c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


temperature  humidity  windy  play  outlook_overcast  outlook_rainy  \
0            85        85      0     0               0.0            0.0   
1            80        90      1     0               0.0            0.0   
2            83        86      0     1               1.0            0.0   
3            70        96      0     1               0.0            1.0   
4            68        80      0     1               0.0            1.0   
5            65        70      1     0               0.0            1.0   
6            64        65      1     1               1.0            0.0   
7            72        95      0     0               0.0            0.0   
8            69        70      0     1               0.0            0.0   
9            75        80      0     1               0.0            1.0   
10           75        70      1     1               0.0            0.0   
11           72        90      1     1               1.0            0.0   
12           81        75      0     1               1.0            0.0   
13           71        91      1     0               0.0            1.0   

    outlook_sunny  
0             1.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
5             0.0  
6             0.0  
7             1.0  
8             1.0  
9             0.0  
10            1.0  
11            0.0  
12            0.0  
13            0.0

In [110]:
df=df.rename(columns={"play":"play_yes"})
df

temperature  humidity  windy  play_yes  outlook_overcast  outlook_rainy  \
0            85        85      0         0               0.0            0.0   
1            80        90      1         0               0.0            0.0   
2            83        86      0         1               1.0            0.0   
3            70        96      0         1               0.0            1.0   
4            68        80      0         1               0.0            1.0   
5            65        70      1         0               0.0            1.0   
6            64        65      1         1               1.0            0.0   
7            72        95      0         0               0.0            0.0   
8            69        70      0         1               0.0            0.0   
9            75        80      0         1               0.0            1.0   
10           75        70      1         1               0.0            0.0   
11           72        90      1         1               1.0            0.0   
12           81        75      0         1               1.0            0.0   
13           71        91      1         0               0.0            1.0   

    outlook_sunny  
0             1.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
5             0.0  
6             0.0  
7             1.0  
8             1.0  
9             0.0  
10            1.0  
11            0.0  
12            0.0  
13            0.0

In [125]:
#x 

x=df.iloc[:,[0,2,3,4,5,6]]
x

temperature  windy  play_yes  outlook_overcast  outlook_rainy  \
0            85      0         0               0.0            0.0   
1            80      1         0               0.0            0.0   
2            83      0         1               1.0            0.0   
3            70      0         1               0.0            1.0   
4            68      0         1               0.0            1.0   
5            65      1         0               0.0            1.0   
6            64      1         1               1.0            0.0   
7            72      0         0               0.0            0.0   
8            69      0         1               0.0            0.0   
9            75      0         1               0.0            1.0   
10           75      1         1               0.0            0.0   
11           72      1         1               1.0            0.0   
12           81      0         1               1.0            0.0   
13           71      1         0               0.0            1.0   

    outlook_sunny  
0             1.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
5             0.0  
6             0.0  
7             1.0  
8             1.0  
9             0.0  
10            1.0  
11            0.0  
12            0.0  
13            0.0

In [112]:
#y humidity

y=df.iloc[:,1]
y

0     85
1     90
2     86
3     96
4     80
5     70
6     65
7     95
8     70
9     80
10    70
11    90
12    75
13    91
Name: humidity, dtype: int64

In [126]:
#train test split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

In [127]:
x_train

temperature  windy  play_yes  outlook_overcast  outlook_rainy  \
13           71      1         0               0.0            1.0   
9            75      0         1               0.0            1.0   
1            80      1         0               0.0            0.0   
7            72      0         0               0.0            0.0   
10           75      1         1               0.0            0.0   
3            70      0         1               0.0            1.0   
0            85      0         0               0.0            0.0   
5            65      1         0               0.0            1.0   
12           81      0         1               1.0            0.0   

    outlook_sunny  
13            0.0  
9             0.0  
1             1.0  
7             1.0  
10            1.0  
3             0.0  
0             1.0  
5             0.0  
12            0.0

In [128]:
y_train

13    91
9     80
1     90
7     95
10    70
3     96
0     85
5     70
12    75
Name: humidity, dtype: int64

In [129]:
x_test

temperature  windy  play_yes  outlook_overcast  outlook_rainy  \
8            69      0         1               0.0            0.0   
6            64      1         1               1.0            0.0   
4            68      0         1               0.0            1.0   
11           72      1         1               1.0            0.0   
2            83      0         1               1.0            0.0   

    outlook_sunny  
8             1.0  
6             0.0  
4             0.0  
11            0.0  
2             0.0

In [130]:
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [131]:
from sklearn.linear_model import LinearRegression

le=LinearRegression()

le.fit(x_train,y_train)

y_predicted=le.predict(x_test)

y_predicted


array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [119]:
#contrast y_predicted and real y values
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64

In [132]:
#check out p values of the columns, then use backward elimination
#p values should be as less as possible 
#predict humidity

import statsmodels.api as sm

# equation for multiple linear regression [   Y=B0+B1X1+B2X2+B3X3+ERROR_RATE ]
# add b0 value here 

BO=np.append(arr=np.ones((14,1)).astype(int),values=df,axis=1)
BO


array([[ 1., 85., 85.,  0.,  0.,  0.,  0.,  1.],
       [ 1., 80., 90.,  1.,  0.,  0.,  0.,  1.],
       [ 1., 83., 86.,  0.,  1.,  1.,  0.,  0.],
       [ 1., 70., 96.,  0.,  1.,  0.,  1.,  0.],
       [ 1., 68., 80.,  0.,  1.,  0.,  1.,  0.],
       [ 1., 65., 70.,  1.,  0.,  0.,  1.,  0.],
       [ 1., 64., 65.,  1.,  1.,  1.,  0.,  0.],
       [ 1., 72., 95.,  0.,  0.,  0.,  0.,  1.],
       [ 1., 69., 70.,  0.,  1.,  0.,  0.,  1.],
       [ 1., 75., 80.,  0.,  1.,  0.,  1.,  0.],
       [ 1., 75., 70.,  1.,  1.,  0.,  0.,  1.],
       [ 1., 72., 90.,  1.,  1.,  1.,  0.,  0.],
       [ 1., 81., 75.,  0.,  1.,  1.,  0.,  0.],
       [ 1., 71., 91.,  1.,  0.,  0.,  1.,  0.]])

In [133]:
df

temperature  humidity  windy  play_yes  outlook_overcast  outlook_rainy  \
0            85        85      0         0               0.0            0.0   
1            80        90      1         0               0.0            0.0   
2            83        86      0         1               1.0            0.0   
3            70        96      0         1               0.0            1.0   
4            68        80      0         1               0.0            1.0   
5            65        70      1         0               0.0            1.0   
6            64        65      1         1               1.0            0.0   
7            72        95      0         0               0.0            0.0   
8            69        70      0         1               0.0            0.0   
9            75        80      0         1               0.0            1.0   
10           75        70      1         1               0.0            0.0   
11           72        90      1         1               1.0            0.0   
12           81        75      0         1               1.0            0.0   
13           71        91      1         0               0.0            1.0   

    outlook_sunny  
0             1.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
5             0.0  
6             0.0  
7             1.0  
8             1.0  
9             0.0  
10            1.0  
11            0.0  
12            0.0  
13            0.0

In [134]:
#create a list for each column in df and eliminate them to reach most proper columns for regression
X_list=df.iloc[:,[0,2,3,4,5,6]].values
X_list=np.array(X_list,dtype=float)
X_list

array([[85.,  0.,  0.,  0.,  0.,  1.],
       [80.,  1.,  0.,  0.,  0.,  1.],
       [83.,  0.,  1.,  1.,  0.,  0.],
       [70.,  0.,  1.,  0.,  1.,  0.],
       [68.,  0.,  1.,  0.,  1.,  0.],
       [65.,  1.,  0.,  0.,  1.,  0.],
       [64.,  1.,  1.,  1.,  0.,  0.],
       [72.,  0.,  0.,  0.,  0.,  1.],
       [69.,  0.,  1.,  0.,  0.,  1.],
       [75.,  0.,  1.,  0.,  1.,  0.],
       [75.,  1.,  1.,  0.,  0.,  1.],
       [72.,  1.,  1.,  1.,  0.,  0.],
       [81.,  0.,  1.,  1.,  0.,  0.],
       [71.,  1.,  0.,  0.,  1.,  0.]])

In [123]:
#create y for the column to be predicted 
y=df.iloc[:,1]
y

0     85
1     90
2     86
3     96
4     80
5     70
6     65
7     95
8     70
9     80
10    70
11    90
12    75
13    91
Name: humidity, dtype: int64

In [135]:
model=sm.OLS(y,X_list).fit()
model.summary()

c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Fri, 17 May 2024   Prob (F-statistic):              0.661
Time:                        01:21:08   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4920      0.597      0.825      0.433      -0.884       1.868
x2            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x3            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x4            52.3891     50.214      1.043      0.327     -63.404     168.183
x5            55.6337     45.233      1.230      0.254     -48.673     159.940
x6            49.4291     48.337      1.023      0.336     -62.035     160.893
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [138]:
#in backward elimination, x2 is eliminated,windy
X_list=df.iloc[:,[0,3,4,5,6]].values
X_list=np.array(X_list,dtype=float)


model=sm.OLS(y,X_list).fit()
model.summary()


c:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Fri, 17 May 2024   Prob (F-statistic):              0.546
Time:                        01:27:25   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.6484      0.506      1.282      0.232      -0.496       1.793
x2            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x3            36.6564     39.905      0.919      0.382     -53.615     126.927
x4            41.9135     36.464      1.149      0.280     -40.573     124.400
x5            35.1064     39.339      0.892      0.395     -53.884     124.097
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [143]:
#train model again and learn the difference
x_train

temperature  play_yes  outlook_overcast  outlook_rainy  outlook_sunny
13           71         0               0.0            1.0            0.0
9            75         1               0.0            1.0            0.0
1            80         0               0.0            0.0            1.0
7            72         0               0.0            0.0            1.0
10           75         1               0.0            0.0            1.0
3            70         1               0.0            1.0            0.0
0            85         0               0.0            0.0            1.0
5            65         0               0.0            1.0            0.0
12           81         1               1.0            0.0            0.0

In [142]:
#delete windy col from x_train
x_train.drop(columns=["windy"],inplace=True)
x_train

KeyError: "['windy'] not found in axis"

In [145]:
x_test

temperature  windy  play_yes  outlook_overcast  outlook_rainy  \
8            69      0         1               0.0            0.0   
6            64      1         1               1.0            0.0   
4            68      0         1               0.0            1.0   
11           72      1         1               1.0            0.0   
2            83      0         1               1.0            0.0   

    outlook_sunny  
8             1.0  
6             0.0  
4             0.0  
11            0.0  
2             0.0

In [146]:
#delete windy col from x_test
x_test.drop(columns=["windy"],inplace=True)
x_test

temperature  play_yes  outlook_overcast  outlook_rainy  outlook_sunny
8            69         1               0.0            0.0            1.0
6            64         1               1.0            0.0            0.0
4            68         1               0.0            1.0            0.0
11           72         1               1.0            0.0            0.0
2            83         1               1.0            0.0            0.0

In [147]:
#linear regression with enhanced model

le.fit(x_train,y_train)
y_predicted_new=le.predict(x_test)
y_predicted_new

array([77.98135142, 68.29304916, 81.05037539, 71.44926132, 75.78905304])

In [149]:
y_predicted

array([84.45365573, 63.93839954, 85.76050662, 64.21013241, 75.06793322])

In [150]:
#system enhanced
y_test

8     70
6     65
4     80
11    90
2     86
Name: humidity, dtype: int64